name: Build interactive map
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm run build
    - name: save build data
      uses: actions/upload-artifact@v3
      with:
        name: upload-build
        path: |
          build
